import { Interaction } from 'discord.js'
import { isNil } from 'ramda'
import { Bot } from '../bot'
import { addedToInstantQueue, addedToQueue } from '../embeds/addedToQueue'
import { BotEvent, QueueItems } from '../types'

const botEvent: BotEvent = {
    name: 'Button Handler - Imagine Regenerate',
    event: 'interactionCreate',
    once: false,
    async execute(bot: Bot, interaction: Interaction) {
        if (!interaction.isButton()) return
        if (interaction.customId !== 'button-imagine-result-regenerate') return

        const referenceQueueItem = bot.findLatestQueueItemReferenceByMessageSnowflake(interaction.message.id)

        if (isNil(referenceQueueItem)) {
            await interaction.reply({
                ephemeral: true,
                content: 'There is no reference of this image generation. Most likely, this generation is too old to modify.'
            })
            
            return
        }

        if (interaction.user.id !== referenceQueueItem.discordCallerSnowflake) {
            await interaction.reply({
                ephemeral: true,
                content: 'You can not modify content generated by other users.'
            })

            return
        }

        const queueItem = new QueueItems.RegeneratedQueueItem.RegeneratedQueueItem({
            discordCallerSnowflake: interaction.user.id.toString(),
            discordInteraction: referenceQueueItem.discordInteraction,
            discordMessageSnowflake: referenceQueueItem.discordMessageSnowflake,
            prompt: referenceQueueItem.prompt,
            height: referenceQueueItem.height,
            width: referenceQueueItem.width,
            initImage: referenceQueueItem.initImage,
            mask: referenceQueueItem.mask,
            promptStrength: referenceQueueItem.promptStrength,
            guidanceScale: referenceQueueItem.guidanceScale,
            numInferenceSteps: referenceQueueItem.numInferenceSteps
        })

        // Remove old attachment
        await interaction.message.removeAttachments()

        if (bot.stableDiffusion.isProcessing() || bot.hasQueue()) {
            const queuePos = bot.addQueuedQueueItem(queueItem)

            await referenceQueueItem.discordInteraction.editReply({
                embeds: addedToQueue(queueItem, queuePos).embeds,
                components: []
            })
        } else {
            bot.addQueuedQueueItem(queueItem)

            await referenceQueueItem.discordInteraction.editReply({
                embeds: addedToInstantQueue(queueItem).embeds,
                components: []
            })
        }
    }
}

export default botEvent
